package com.hzdy.entity;

import java.util.Date;

public class ShiroSession {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rainbow_shiro_session.shiro_session_id
     *
     * @mbggenerated Fri Feb 10 15:43:02 CST 2017
     */
    private String shiroSessionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rainbow_shiro_session.shiro_session
     *
     * @mbggenerated Fri Feb 10 15:43:02 CST 2017
     */
    private String shiroSession;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rainbow_shiro_session.create_time
     *
     * @mbggenerated Fri Feb 10 15:43:02 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rainbow_shiro_session.shiro_session_id
     *
     * @return the value of rainbow_shiro_session.shiro_session_id
     *
     * @mbggenerated Fri Feb 10 15:43:02 CST 2017
     */
    public String getShiroSessionId() {
        return shiroSessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rainbow_shiro_session.shiro_session_id
     *
     * @param shiroSessionId the value for rainbow_shiro_session.shiro_session_id
     *
     * @mbggenerated Fri Feb 10 15:43:02 CST 2017
     */
    public void setShiroSessionId(String shiroSessionId) {
        this.shiroSessionId = shiroSessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rainbow_shiro_session.shiro_session
     *
     * @return the value of rainbow_shiro_session.shiro_session
     *
     * @mbggenerated Fri Feb 10 15:43:02 CST 2017
     */
    public String getShiroSession() {
        return shiroSession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rainbow_shiro_session.shiro_session
     *
     * @param shiroSession the value for rainbow_shiro_session.shiro_session
     *
     * @mbggenerated Fri Feb 10 15:43:02 CST 2017
     */
    public void setShiroSession(String shiroSession) {
        this.shiroSession = shiroSession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rainbow_shiro_session.create_time
     *
     * @return the value of rainbow_shiro_session.create_time
     *
     * @mbggenerated Fri Feb 10 15:43:02 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rainbow_shiro_session.create_time
     *
     * @param createTime the value for rainbow_shiro_session.create_time
     *
     * @mbggenerated Fri Feb 10 15:43:02 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}